agent:
  server_url: https://localhost:27000
  registration_url: https://localhost:55000
  retry_interval: 30s
inventory:
  enabled: true
  interval: 1h
  scan_on_start: true
  hardware: true
  os: true
  network: true
  packages: true
  ports: true
  ports_all: true
  processes: true
  hotfixes: true
logcollector:
  enabled: true
  localfiles:
    - /var/log/auth.log
  reload_interval: 1m
  file_wait: 500ms
