name: Compile and Run Tests

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg lsb-release software-properties-common \
          libltdl-dev libsystemd-dev
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get update
        sudo apt-get install -y clang-tidy-18 autopoint libtool zlib1g-dev \
          libgcrypt20-dev libpopt-dev libmagic-dev libsqlite3-dev \
          liblua5.4-dev gettext libarchive-dev
      shell: bash

    - name: Set up Binary caching
      uses: ./.github/actions/vcpkg_related/5_builderpackage_vcpkg
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Compile Action
      uses: ./.github/actions/5_testintegration_compile
      with:
        path: src/
        build_path: build-${{ matrix.os }}/

    - name: Run Tests
      uses: ./.github/actions/5_testintegration_ctest
      with:
        path: build-${{ matrix.os }}/
